title: "Trying to fit a masked minimum"
trainer: "MaskTrainer"
random_seed: 42
data_dir: "data"
mask_type: "icon"
modules:
  models: ["model"]
  optims: ["optim"]
logging:
  training_progress: False
max_num_epochs: 300
good_and_bad_val_acc_diff_threshold: 0.01
diff_threshold_num_warmup_epochs: 30
val_freq_epochs: 10

hp:
  model_name: "resnet18"
  icon_file_path: "custom-icons/mona-lisa.png"
  should_center_origin: true

  norm_l2_coef: 1.
  ort_l2_coef: 10.
  batch_size: 512

  num_good_cells_per_update: 10
  num_bad_cells_per_update: 10
  grad_clip_threshold: 10

  optim:
    type: "SGD"
    kwargs: {lr: 1, nesterov: true, momentum: 0.9, weight_decay: 0.005}
    scheduler:
      type: "triangle_lr"
      kwargs: {knots: [0, 5, 50], values: [0.0001, 0.4, 0.001]}
hpo:
  num_parallel_experiments_per_gpu: 1
  scheme: "grid-search"
  grid:
    parametrization_type: ["simple", "up_orthogonal"]
    neg_loss_clip_threshold: [0.5, 2., 5.]
