trainer: "MaskTrainer"
random_seed: 42
data_dir: "data"
mask_type: "icon"
modules:
  models: ["model"]
  optims: ["optim"]
max_num_epochs: 100
good_and_bad_val_acc_diff_threshold: 0.01
diff_threshold_num_warmup_epochs: 50
val_freq_epochs: 10
logging:
  training_progress: True
hp:
  model_name: "fast_resnet"
  icon_file_path: "custom-icons/mona-lisa.png"
  should_center_origin: true

  batch_size: 512
  num_good_cells_per_update: 50
  num_bad_cells_per_update: 50
  parametrization_type: "up_orthogonal"
  grad_clip_threshold: 10
  neg_loss_clip_threshold: 2.

hpo:
  num_parallel_experiments_per_gpu: 1
  scheme: "grid-search"
  grid:
    optim: [
      {type: "adam", kwargs: {lr: 0.00001}},
      {type: "adam", kwargs: {lr: 0.00005}},
      {type: "adam", kwargs: {lr: 0.0001}},
      {type: "adam", kwargs: {lr: 0.0005}},
      {type: "adam", kwargs: {lr: 0.001}},
    ]
