title: "Trying to fit a masked minimum"
trainer: "MaskTrainer"
random_seed: 42
data_dir: "data"
model_name: "conv"
mask_type: "icon"
modules:
  models: ["model"]
  optims: ["optim"]
logging:
  training_progress: False
max_num_epochs: 100
# max_num_iters: 1
good_val_acc_stop_threshold: 0.2
bad_val_acc_stop_threshold: 0.9
val_freq_epochs: 1
solution_vis:
  granularity:
    x: 30
    y: 30
  padding: 5
# solution_vis:
#   granularity:
#     x: 3
#     y: 3
#   padding: 1
hpo:
  num_parallel_experiments_per_gpu: 2
  scheme: "random-search"
  num_experiments: 500
  grid:
    norm_l2_coef: [1.]
    ort_l2_coef: [10.]
    batch_size: [256]
    grad_clip_threshold: [10]
    negative_loss_coef: [1.]
    parametrization_type: ["simple", "difference", "up_orthogonal"]
    num_good_cells_per_update: [25, 50]
    num_bad_cells_per_update: [25, 50]
    should_resize_icon: [false]
    should_center_origin: [true, false]
    lr: [0.005, 0.001, 0.0005, 0.00025, 0.0001, 0.00005, 0.00001]
    scaling: [0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.15, 0.2, 0.25]
    neg_loss_clip_threshold: [1, 5, 10, 100]
    grad_clip_threshold: [1, 5, 10, 100]
    icon_file_path: ["custom-icons/mona-lisa.png"]
    conv_model_config: [
      {conv_sizes: [1, 8, 32, 64], dense_sizes: [576, 1024, 512, 128], use_dropout: true},
      {conv_sizes: [1, 8, 32, 64], dense_sizes: [576, 1024, 512, 128], use_dropout: false},
      {conv_sizes: [1, 8, 32, 64], dense_sizes: [576, 512, 128], use_dropout: true},
      {conv_sizes: [1, 8, 32, 64], dense_sizes: [576, 512, 128], use_dropout: false},
      {conv_sizes: [1, 8, 32, 64], dense_sizes: [576, 1024, 128], use_dropout: true},
      {conv_sizes: [1, 8, 32, 64], dense_sizes: [576, 1024, 128], use_dropout: false},

      {conv_sizes: [1, 8, 32], dense_sizes: [1568, 1024, 512, 128], use_dropout: true},
      {conv_sizes: [1, 8, 32], dense_sizes: [1568, 1024, 512, 128], use_dropout: false},
      {conv_sizes: [1, 8, 32], dense_sizes: [1568, 512, 128], use_dropout: true},
      {conv_sizes: [1, 8, 32], dense_sizes: [1568, 512, 128], use_dropout: false},
      {conv_sizes: [1, 8, 32], dense_sizes: [1568, 1024, 128], use_dropout: true},
      {conv_sizes: [1, 8, 32], dense_sizes: [1568, 1024, 128], use_dropout: false},
    ]
