title: "Trying to fit a masked minimum on CIFAR10"
trainer: "MaskTrainer"
random_seed: 42
data_dir: "data"
model_name: "vgg"
mask_type: "icon"
modules:
  models: ["model"]
  optims: ["optim"]
logging:
  training_progress: False
good_and_bad_val_acc_diff_threshold: 0.01
diff_threshold_num_warmup_epochs: 25
val_freq_epochs: 1

max_num_epochs: 50
solution_vis:
  granularity:
    x: 50
    y: 50
  padding: 5

# For debug purposes
# max_num_iters: 1
# solution_vis:
#   granularity:
#     x: 3
#     y: 3
#   padding: 1

hp:
  should_resize_icon: true
  target_icon_size: [50, 50]
  icon_file_path: "main-icons/duck-side-view-outline.png"
  should_center_origin: true
  norm_l2_coef: 1.
  ort_l2_coef: 10.
  batch_size: 256
  dataset: "CIFAR10"
  num_input_channels: 3
  optim: "adam"
  num_good_cells_per_update: 50
  num_bad_cells_per_update: 50
  n_input_channels: 3
hpo:
  num_parallel_experiments_per_gpu: 2
  scheme: "random-search"
  num_experiments: 100
  grid:
    negative_loss_coef: [0.5, 1., 5.]
    parametrization_type: ["simple", "up_orthogonal"]
    lr: [0.005, 0.001, 0.0005, 0.00025, 0.0001, 0.00005]
    neg_loss_clip_threshold: [0.5, 1., 2., 3., 4., 5.]
    grad_clip_threshold: [1, 5, 10, 25, 100]
    use_bn: [true, false]