trainer: "ClassifierTrainer"
random_seed: 42
data_dir: "data"
modules:
  models: ["model"]
  optims: ["optim"]
max_num_epochs: 25
val_freq_epochs: 5
hp:
  batch_size: 512
  model_name: "fast_resnet"
  optim:
    type: "SGD"
    kwargs:
      lr: 1 # Setting to 1 since we are using LR scheduler
      nesterov: true
      momentum: 0.9
      weight_decay: 0.25
    scheduler:
      type: "triangle_lr"
      kwargs:
        knots: [0, 5, 25]
        values: [0., 0.0008, 0.]

