title: "Trying to fit an elbow between minima"
trainer: "ElbowTrainerWrapper"
random_seed: 42
data_dir: "data"
max_num_epochs: 1
val_freq_epochs: 1
hp:
  batch_size: 256
  lr: 0.001
  dist_reg_coef: 0.01
