title: "Trying to fit an ensemble with MPO"
trainer: "EnsembleTrainer"
random_seed: 42
data_dir: "data"
modules:
  models: ["model"]
  optims: ["optim"]
val_freq_epochs: 5
max_num_epochs: 50
checkpoint:
  save_last: true
hp:
  model_name: "fast_resnet"
  n_input_channels: 3
  ensemble_type: "plane"
  batch_size: 512
  optim: "adam"
  grad_clip_threshold: 10
  coords_init_strategy: "standard_uniform"
  dataset: "CIFAR10"
  decorrelation_type: "none"
  decorrelation_coef: 0.01
  num_models: 10
  num_models_per_update: 10

  # Optimizer params
  optim:
    type: "SGD"
    kwargs:
      lr: 1 # Setting to 1 since we are using LR scheduler
      nesterov: true
      momentum: 0.9
      weight_decay: 0.25
    scheduler:
      type: "triangle_lr"
      kwargs:
        knots: [0, 5, 50]
        values: [0., 0.1, 0.]

