title: "Trying to fit an ensemble with MPO"
trainer: "EnsembleTrainer"
random_seed: 42
data_dir: "data"
model_name: "conv"
modules:
  models: ["model"]
  optims: ["optim"]
val_freq_epochs: 1
max_num_epochs: 100
checkpoint:
  freq_epochs: 10
hp:
  ensemble_type: "mapping"
  ensemble_config:
    dense_sizes: [100, 3]
    activation: "relu"
  batch_size: 512
  optim: "adam"
  grad_clip_threshold: 100
  coords_init_strategy: "standard_uniform"
  dataset: "FashionMNIST"
  decorrelation_type: "none"
  decorrelation_coef: 0.01
  conv_model_config:
    conv_sizes: [1, 16, 128]
    dense_sizes: [128]
    adaptive_pool_size: [1, 1]
    use_bn: false
    use_maxpool: true
  lr: 0.01
  num_models: 3
  num_models_per_update: 3
