trainer: "EnsembleTrainer"
random_seed: 42
data_dir: "data"
modules:
  models: ["model"]
  optims: ["optim"]
val_freq_epochs: 5
max_num_epochs: 40
checkpoint:
  save_last: true
hp:
  ensemble_type: "plane"
  decorrelation_type: "coords_distance"
  decorrelation_coef: 0.5
  decorrelation_loss_clamp: 1.
  coords_init_strategy: "isotropic_normal"
  model_name: "fast_resnet"
  n_input_channels: 3
  batch_size: 512
  grad_clip_threshold: 1000
  dataset: "CIFAR10"
  num_models: 3
  num_models_per_update: 3

  # Optimizer params
  optim:
    type: "SGD"
    kwargs:
      lr: 1 # Setting to 1 since we are using LR scheduler
      nesterov: true
      momentum: 0.9
      weight_decay: 0.1
    scheduler:
      type: "triangle_lr"
      kwargs:
        knots: [0, 5, 30]
        values: [0., 0.001, 0.0001]
