title: "Trying to fit an ensemble with MPO"
trainer: "EnsembleTrainer"
random_seed: 42
data_dir: "data"
model_name: "fast_resnet"
modules:
  models: ["model"]
  optims: ["optim"]
val_freq_epochs: 1
max_num_epochs: 100
checkpoint:
  freq_epochs: 10
hp:
  n_input_channels: 3
  ensemble_type: "plane"
  batch_size: 512
  optim: "adam"
  grad_clip_threshold: 10
  coords_init_strategy: "standard_uniform"
  dataset: "CIFAR10"
  decorrelation_type: "none"
  decorrelation_coef: 0.01
  num_models: 1
  num_models_per_update: 1

  # Optimizer params
  optim:
    type: "SGD"
    kwargs:
      lr: 1 # Setting to 1 since we are using LR scheduler
      nesterov: true
      momentum: 0.9
      weight_decay: 0.05
    scheduler:
      type: "triangle_lr"
      kwargs:
        knots: [0, 5, 50]
        values: [0.0001, 0.4, 0.001]

