title: "Trying to fit different simple masks"
trainer: "MaskTrainer"
random_seed: 42
data_dir: "data"
model_name: "conv"
mask_type: "icon"
modules:
  models: ["model"]
  optims: ["optim"]
logging:
  training_progress: False
# good_val_acc_stop_threshold: 0.2
# bad_val_acc_stop_threshold: 0.9
good_and_bad_val_acc_diff_threshold: 0.01
diff_threshold_num_warmup_epochs: 30
val_freq_epochs: 1
max_num_epochs: 100
solution_vis:
  granularity:
    x: 32
    y: 32
  padding: 5
# max_num_iters: 1
# solution_vis:
#   granularity:
#     x: 3
#     y: 3
#   padding: 1
hp:
  norm_l2_coef: 10.
  ort_l2_coef: 10.
  batch_size: 512
  negative_loss_coef: 1.0
  num_good_cells_per_update: 50
  num_bad_cells_per_update: 50
  should_resize_icon: true
  should_center_origin: true
  target_icon_size: [50, 50]
  optim: "adam"
  grad_clip_threshold: 100
  conv_model_config:
    conv_sizes: [1, 8, 32, 64]
    dense_sizes: [576, 128]
    use_bn: false
hpo:
  num_parallel_experiments_per_gpu: 7
  scheme: "grid-search"
  grid:
    lr: [0.0005, 0.00025, 0.0001, 0.00005]
    neg_loss_clip_threshold: [2, 5]
    parametrization_type: ["simple", "up_orthogonal"]
    icon_file_path: [
      "main-icons/041-star of david.png",
      "main-icons/balalaika (1).png",
      "main-icons/batman (1).png",
      "main-icons/batman-logo.png",
      "main-icons/black-evil-cat.png",
      "main-icons/duck-side-view-outline.png",
      "main-icons/eiffel-tower.png",
      "main-icons/freemasonry.png",
      "main-icons/kremlin.png",
      "main-icons/lego.png",
      "main-icons/locomotive.png",
      "main-icons/r2d2.png",
      "main-icons/risk-skull.png",
      "main-icons/start-up (1).png"
    ]
