title: "Trying to fit different simple masks"
trainer: "MaskTrainer"
random_seed: 42
data_dir: "data"
mask_type: "icon"
modules:
  models: ["model"]
  optims: ["optim"]
logging:
  training_progress: False
good_and_bad_val_acc_diff_threshold: 0.01
diff_threshold_num_warmup_epochs: 30
val_freq_epochs: 1
max_num_epochs: 100
checkpoint:
  freq_epochs: 50
hp:
  dataset: "FashionMNIST"
  norm_l2_coef: 10.
  ort_l2_coef: 10.
  batch_size: 512
  negative_loss_coef: 1.0
  num_good_cells_per_update: 50
  num_bad_cells_per_update: 50
  should_resize_icon: true
  should_center_origin: true
  target_icon_size: [50, 50]
  optim: "adam"
  grad_clip_threshold: 100

  parametrization_type: "up_orthogonal"
  neg_loss_clip_threshold: 2.5

  model_name: "conv"
  conv_model_config:
    conv_sizes: [1, 8, 32, 64]
    dense_sizes: [1024, 128]
    use_bn: false
    use_maxpool: true

hpo:
  num_parallel_experiments_per_gpu: 1
  scheme: "grid-search"
  grid:
    icon_file_path: [
      # "more-icons/smiling-emoticon-square-face.png",
      # "more-icons/spooky.png"
      "more-icons/hand-1.png",
      "more-icons/hand-2.png",
    ]
    optim: [
      {type: "adam", kwargs: {"lr": 0.00025}},
      {type: "adam", kwargs: {"lr": 0.0001}},
    ]
