title: "Trying to fit a masked minimum"
trainer: "MaskTrainer"
random_seed: 42
data_dir: "data"
model_name: "simple"
mask_type: "icon"
modules:
  models: ["model"]
  optims: ["optim"]
logging:
  training_progress: False
max_num_epochs: 100
# max_num_iters: 1
good_val_acc_stop_threshold: 0.2
bad_val_acc_stop_threshold: 0.9
val_freq_epochs: 1
solution_vis:
  granularity:
    x: 30
    y: 30
  padding: 5
hp:
  norm_reg_coef: 1.
  ort_reg_coef: 1.
  batch_size: 256
  grad_clip_threshold: 10
  negative_loss_coef: 1.0
  parametrization_type: "simple"
  square_size: 30
  num_good_cells_per_update: 25
  num_bad_cells_per_update: 25
  icon_size: [32, 32]
hpo:
  num_parallel_experiments_per_gpu: 2
  scheme: "random-search"
  num_experiments: 500
  grid:
    lr: [0.001, 0.0005, 0.0001, 0.00001]
    scaling: [0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.5, 0.75, 1.]
    should_center_origin: [true, false]
    neg_loss_clip_threshold: [1, 5, 10, 100]
    grad_clip_threshold: [1, 5, 10, 100]
    icon_file_path: [
      "icons/001-cancer.png",
      "icons/002-heart.png",
      "icons/003-air.png",
      "icons/004-om.png",
      "icons/005-leo.png",
      "icons/006-cross.png",
      "icons/007-moon.png",
      "icons/008-pentagram.png",
      "icons/009-aquarius.png",
      "icons/010-jupiter.png",
      "icons/011-copper.png",
      "icons/012-gemini.png",
      "icons/013-venus.png",
      "icons/014-crystal ball.png",
      "icons/015-earth.png",
      "icons/016-mars.png",
      "icons/017-sulphur.png",
      "icons/018-lotus.png",
      "icons/019-mercury.png",
      "icons/020-scorpio.png",
      "icons/021-crystal.png",
      "icons/022-oxygen.png",
      "icons/023-gemini.png",
      "icons/024-rune.png",
      "icons/025-water.png",
      "icons/026-aries.png",
      "icons/027-pluto.png",
      "icons/028-death.png",
      "icons/029-hand.png",
      "icons/030-rune.png",
      "icons/031-saturn.png",
      "icons/032-yin yang.png",
      "icons/033-pendulum.png",
      "icons/034-virgo.png",
      "icons/035-earth.png",
      "icons/036-life.png",
      "icons/037-libra.png",
      "icons/038-skull.png",
      "icons/039-warning.png",
      "icons/040-sun.png",
      "icons/041-star of david.png",
      "icons/042-ankh.png",
      "icons/043-hand.png",
      "icons/044-candle.png",
      "icons/045-taurus.png",
      "icons/046-capricorn.png",
      "icons/047-ceres.png",
      "icons/048-sagittarius.png",
      "icons/049-triangle.png",
      "icons/050-uranus.png"
    ]
