title: "Trying to fit a masked minimum"
trainer: "MaskTrainer"
random_seed: 42
data_dir: "data"
model_name: "simple"
modules:
  models: ["model"]
  optims: ["optim"]
max_num_epochs: 10
val_freq_epochs: 1
hp:
  batch_size: 256
  lr: 0.001
  clip_threshold: 2
  negative_loss_coef: 1.
  ort_reg_coef: 1.
  norm_reg_coef: 1.
  scaling: 1.
  num_cells_in_update:
    good: 5
    bad: 5
hpo:
  num_parallel_experimens_per_gpu: 6
  grid:
    square_size: [3, 5, 10, 20, 30, 40, 50, 75, 100, 250]
