title: "Trying to fit a masked minimum"
trainer: "MaskTrainer"
random_seed: 42
data_dir: "data"
model_name: "simple"
mask_type: "square"
modules:
  models: ["model"]
  optims: ["optim"]
max_num_epochs: 100
val_freq_epochs: 1
minima_visualization_granularity: 30
hp:
  batch_size: 256
  lr: 0.01
  clip_threshold: 2
  grad_clip_threshold: 100.
  negative_loss_coef: 1.
  # scaling: 1.
  square_size: 30
  num_good_cells_per_update: 5
  num_bad_cells_per_update: 5
hpo:
  num_parallel_experiments_per_gpu: 10
  grid:
    scaling: [0.01, 0.1, 0.25, 0.5, 0.9, 1., 1.1, 1.5, 2.5, 5., 10., 100.]
