title: "Trying to fit a masked minimum"
trainer: "MaskTrainer"
random_seed: 42
data_dir: "data"
model_name: "simple"
mask_type: "icon"
modules:
  models: ["model"]
  optims: ["optim"]
logging:
  training_progress: False
max_num_epochs: 100
# max_num_iters: 1
good_val_acc_stop_threshold: 0.2
bad_val_acc_stop_threshold: 0.9
val_freq_epochs: 1
solution_vis:
  granularity:
    x: 30
    y: 30
  padding: 5
hp:
  norm_reg_coef: 1.
  ort_reg_coef: 1.
  batch_size: 256
  grad_clip_threshold: 10
  negative_loss_coef: 1.0
  parametrization_type: "simple"
  num_good_cells_per_update: 25
  num_bad_cells_per_update: 25
  should_resize_icon: false
hpo:
  num_parallel_experiments_per_gpu: 5
  scheme: "random-search"
  num_experiments: 500
  grid:
    lr: [0.001, 0.0005, 0.0001, 0.00001]
    scaling: [0.01, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.5, 0.75, 1.]
    should_center_origin: [true, false]
    neg_loss_clip_threshold: [1, 5, 10, 100]
    grad_clip_threshold: [1, 5, 10, 100]
    icon_file_path: [
      "custom-icons/mona-lisa.png",
      "custom-icons/batman-logo-1.png",
      "custom-icons/batman-logo-2.png",
      "custom-icons/goose.png",
      "custom-icons/putin.png",
    ]
