title: "Trying to fit a masked minimum"
trainer: "MaskTrainer"
random_seed: 42
data_dir: "data"
modules:
  models: ["model"]
  optims: ["optim"]
max_num_epochs: 100
val_freq_epochs: 1
hp:
  batch_size: 256
  lr: 0.001
  clip_threshold: 2
  negative_loss_coef: 1.
  ort_reg_coef: 1.
  norm_reg_coef: 1.
  scaling: 1.
  num_cells_in_update:
    good: 5
    bad: 5
hpo:
  grid:
    square_size: [7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97]
