title: "Fitting random squares"
trainer: "MaskTrainer"
random_seed: 42
data_dir: "data"
model_name: "conv"
mask_type: "randomly_filled_square"
modules:
  models: ["model"]
  optims: ["optim"]
logging:
  training_progress: False
max_num_epochs: 100
solution_vis:
  granularity:
    x: 30
    y: 30
  padding: 5
# max_num_iters: 1
# solution_vis:
#   granularity:
#     x: 3
#     y: 3
#   padding: 1
good_val_acc_stop_threshold: 0.2
bad_val_acc_stop_threshold: 0.9
val_freq_epochs: 1
hp:
  norm_l2_coef: 10.
  ort_l2_coef: 10.
  batch_size: 512
  grad_clip_threshold: 10
  negative_loss_coef: 1.0
  parametrization_type: "simple"
  num_good_cells_per_update: 25
  num_bad_cells_per_update: 25
  should_center_origin: true
  neg_loss_clip_threshold: 5
  grad_clip_threshold: 25
hpo:
  num_parallel_experiments_per_gpu: 10
  scheme: "grid-search"
  grid:
    lr: [0.001, 0.0005, 0.0001]
    scaling: [0.01, 0.1, 0.25]
    fill_prob: [0., 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.]
    square_size: [3, 5, 7, 9, 11, 15, 25, 50, 100]
