title: "Trying to fit different simple masks"
trainer: "MaskTrainer"
random_seed: 42
data_dir: "data"
model_name: "conv"
mask_type: "icon"
modules:
  models: ["model"]
  optims: ["optim"]
logging:
  training_progress: False
good_and_bad_val_acc_diff_threshold: 0.01
diff_threshold_num_warmup_epochs: 3
val_freq_epochs: 1
checkpoint:
  freq_iters: 3
max_num_iters: 10
solution_vis:
  granularity:
    x: 3
    y: 3
  padding: 1
hp:
  norm_l2_coef: 10.
  ort_l2_coef: 10.
  batch_size: 512
  negative_loss_coef: 1.0
  num_good_cells_per_update: 50
  num_bad_cells_per_update: 50
  should_resize_icon: true
  should_center_origin: true
  target_icon_size: [50, 50]
  optim: "adam"
  grad_clip_threshold: 100
  conv_model_config:
    conv_sizes: [1, 8, 32, 64]
    dense_sizes: [1024, 128]
    use_bn: false
  icon_file_path: "main-icons/r2d2.png"
hpo:
  num_parallel_experiments_per_gpu: 1
  scheme: "random-search"
  num_experiments: 4
  grid:
    lr: [0.0005, 0.00025, 0.0001, 0.00005]
    neg_loss_clip_threshold: [2, 5]
    parametrization_type: ["simple", "up_orthogonal"]
